<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sn</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Snow</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\/\/.+</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([0-9]+)|(0x[0-9A-Fa-f]+)|(0b[0-1]+)|(0o[0-7]+)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>null|true|false</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&amp;|\||\^|~</string>
			<key>name</key>
			<string>keyword.operator.bitwise</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&amp;&amp;|\|\||!</string>
			<key>name</key>
			<string>keyword.operator.logical</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&lt;|\&gt;|\&lt;=|≤|\&gt;=|≥|=|!=|≠</string>
			<key>name</key>
			<string>keyword.operator.relational</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|\-|\*|\/|%</string>
			<key>name</key>
			<string>keyword.operator.mathematical</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:</string>
			<key>name</key>
			<string>keyword.operator.assignment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>class</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>return|if|elsif|else|end|switch|case|break|while</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>self</string>
			<key>name</key>
			<string>variable.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[ \t]*(self)?\.([A-Za-z][a-zA-Z0-9_!?]*)</string>
			<key>name</key>
			<string>variable.instance</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([A-Za-z][a-zA-Z0-9_!?]*)(:)( )*(\(([a-zA-Z0-9_, ]*)\))?( )*\{</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.snow</string>
	<key>uuid</key>
	<string>F75AF252-7C89-410D-9307-F6DF59A3444D</string>
</dict>
</plist>
