<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sn</string>
		<string>☃</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!/.*\bsnow\b</string>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Snow</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.block.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\/\/.+</string>
			<key>name</key>
			<string>comment.line.double-slash.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([0-9]+)|(0x[0-9A-Fa-f]+)|(0b[0-1]+)|(0o[0-7]+)</string>
			<key>name</key>
			<string>constant.numeric.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#[[:alpha:]][[:alnum:]]*</string>
			<key>name</key>
			<string>constant.other.symbol.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(null|true|false)\b</string>
			<key>name</key>
			<string>constant.language.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&amp;|\||\^|~</string>
			<key>name</key>
			<string>keyword.operator.bitwise.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&amp;&amp;|\|\||!</string>
			<key>name</key>
			<string>keyword.operator.logical.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&lt;|\&gt;|\&lt;=|≤|\&gt;=|≥|=|!=|≠|≈|≉|∑|∏|√</string>
			<key>name</key>
			<string>keyword.operator.relational.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*|[-+*\/%]</string>
			<key>name</key>
			<string>keyword.operator.mathematical.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>∈|∉|⊂|⊄|⊆|⊈|∋|∌|⊃|⊅|⊇|⊉|∩|∪</string>
			<key>name</key>
			<string>keyword.operator.set.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:</string>
			<key>name</key>
			<string>keyword.operator.assignment.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>class</string>
			<key>name</key>
			<string>keyword.other.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(return|break|if|unless|elsif|else|switch|case|while|until|end)\b</string>
			<key>name</key>
			<string>keyword.control.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>it</string>
			<key>name</key>
			<string>variable.language.snow</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.instance.snow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((^|\{|;)\s*)(self)?(\.([A-Za-z][a-zA-Z0-9_!?]*))</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.snow</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.snow</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parameters.snow</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.function.snow</string>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parameters.snow</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s*,\s*</string>
					<key>name</key>
					<string>punctuation.separator.parameters.snow</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.snow</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.snow</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.snow</string>
	<key>uuid</key>
	<string>F75AF252-7C89-410D-9307-F6DF59A3444D</string>
</dict>
</plist>
